services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-parking-front
    command: /bin/sh -c "npm run build"
    volumes:
      - .:/app
    networks:
      - qr-parking-network
networks:
  qr-parking-network:
    external: true